// Code generated by mockery v2.46.3. DO NOT EDIT.

package mockport

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageSender is an autogenerated mock type for the MessageSender type
type MockMessageSender struct {
	mock.Mock
}

type MockMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSender) EXPECT() *MockMessageSender_Expecter {
	return &MockMessageSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: ctx, message
func (_m *MockMessageSender) SendMessage(ctx context.Context, message string) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessageSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *MockMessageSender_Expecter) SendMessage(ctx interface{}, message interface{}) *MockMessageSender_SendMessage_Call {
	return &MockMessageSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, message)}
}

func (_c *MockMessageSender_SendMessage_Call) Run(run func(ctx context.Context, message string)) *MockMessageSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageSender_SendMessage_Call) Return(_a0 error) *MockMessageSender_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSender_SendMessage_Call) RunAndReturn(run func(context.Context, string) error) *MockMessageSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSender creates a new instance of MockMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSender {
	mock := &MockMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
