kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "crawlert.fullname" . }}
  labels:
    {{- include "crawlert.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}

